---
- hosts: all
  vars:
    - provision_password: '$6$jIrFfxASDby3HBo9$jVw02IOyoqe0gmOUxmnn.QL99hIjsxsNPkehIqJc903iRU6CKYPLHEieI0Ij9Yp291bZOp4b2krZSYSsfxPur/'
  gather_facts: no
  remote_user: administrator
  become: true

tasks:

- name: Add a new user named provision
  user:
    name: provision
    shell: /bin/bash
    password: "{{ provision_password }}"

- name: Add provision user to the sudoers.
  copy:
    dest: "/etc/sudoers.d/provision"
    content: "provision   ALL=(ALL)   NOPASSWD: ALL"

- name: Deploy ssh key
    authorized_key: user=provision
                    key = "{{ lookup('file',
                    '/home/provision/.ssh/id_rsa.pub') }}"
                    state=present

- name: Disable Password Authentication
    lineinfile: 
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes

-name: Disable Root Login
   lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
    notify:
      - restart ssh


handlers:
  - name: restart ssh
    service:
      name=sshd
      state=restarted



