name: Provision

on:
  repository_dispatch:
    types: [Provision]
jobs:
  provision:
    name: Provision VMs with main playbook.
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout playbook
        uses: actions/checkout@v2
        with:
          ref: 'main'
          
      - name: Checkout Inventory
        uses: actions/checkout@v2
        with:
          repository: xiguazhi/ansible-inventory
          ref: 'main'

      - name: Show current directory
        run: pwd
      - name: Run ansible playbook
        run: ansible-playbook -i ../ansible-inventory/ubuntu.vmware.yml --vault-password-file=${{ secrets.vault_pwd}} basic-playbook.yml
